name: 'JIRA Ticket'
description: 'Links JIRA ticket and moves tasks IN PR if not already there'
inputs:
  host:
    description: 'Atlassian JIRA host'
    required: true
  board:
    description: 'JIRA Board'
    required: true
outputs:
  test: # id of output
    description: 'test'
runs:
  using: 'node16'
  main: 'dist/index.js'