name: 'JIRA Ticket'
description: 'Links JIRA ticket and moves tasks IN PR if not already there'
inputs:
  jira-host:
    description: 'Atlassian JIRA host'
    required: true
  jira-board:
    description: 'JIRA Board'
    required: true
  repo-token:
    description: 'Github Repo Token'
    required: true
outputs:
  test: # id of output
    description: 'test'
runs:
  using: 'node16'
  main: 'dist/index.js'