name: 'JIRA Ticket'
description: 'Links JIRA ticket and moves tasks IN PR if not already there'
inputs:
  jira-host:
    description: 'Atlassian JIRA host'
    required: true
  jira-board:
    description: 'JIRA Board'
    required: true
  jira-email:
    description: 'JIRA Email'
    required: true
  jira-token:
    description: 'JIRA Token'
    required: true
  jira-in-progress-id:
    description: 'JIRA In Progress Status ID'
    required: true
  jira-in-pr-id:
    description: 'JIRA In PR Status ID'
    required: true
  github-token:
    description: 'Github Repo Token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'